name: 3-Tier CD Pipeline

on:
  workflow_run:
    workflows: ["3-Tier CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-ec2:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout Code on EC2
        uses: actions/checkout@v4

      - name: Log in to Docker Hub on EC2
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Deploy 3-Tier App with Docker Compose & Secrets
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          docker compose pull
          docker compose down
          docker compose up -d --remove-orphans